
env:
  - DB=sqlite
  - features = ('features/students_problem_view.feature' 'features/add_bloom_ratings.feature')
- |
  for i in ${features[@]}; do  
    before_script:
      - bundle exec sunspot-solr start -p 8983
    script:
      - RAILS_ENV=test bundle exec rake db:migrate
      - bundle exec rake db:test:prepare
      - bundle exec rake db:seed
      - bundle exec rake sunspot:solr:reindex
      - bundle exec cucumber $i
      - bundle exec rake spec
    after_script:
      - bundle exec sunspot-solr stop
  done
language: ruby
rvm:
  - 2.3.0

addons:
    code_climate:
        repo_token: 9b5e245140aef5f9beedc0f50df30b7530a71d5d490c443e72086593230f9197
